name: Update Gist

on:
  push:
    branches:
      - main  # Это ветка, при изменении которой будет запускаться действие
    paths:
      - main.py  # Путь к файлу, который нужно синхронизировать

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Gist
        run: |
          GIST_ID="d2f631319c4f7c67769a1ad83ebe1d4a"  # ID твоего Gist
          FILE_PATH="main.py"  # Путь к файлу в репозитории
          curl \
            -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d @- https://api.github.com/gists/$GIST_ID <<EOF
            {
              "files": {
                "main.py": {
                  "content": "$(cat $FILE_PATH)"
                }
              }
            }
            EOF
